version: "3.9"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  web:
    restart: on-failure
    build: ./web
    hostname: web
    ports:
      - "81:5000"
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
